# Header
menu:
  Home: /
  Archives: /archives
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/tyrantqiao"
  # weibo: "https://weibo.com/tyrantqiao/home"
#  rss: "#"
  # zhihu: "https://www.zhihu.com/people/bao-jun-qiao"
  qq: "51307521"
  #weixin: "#"
  #jianshu: "#"
  # douban: "https://www.douban.com/people/tyrantqiao/"
  #segmentfault: "#"
  mail: "tyrantqiao@gmail.com"
  facebook: "https://www.facebook.com/TyrantQiao"
  #google: "#"
  #twitter: "#"
  linkedin: "https://www.linkedin.com/in/%E9%BB%84-%E4%B9%94%E9%91%AB-a44179161/"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
url: http://tyrantqiao.github.io
root: /

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '蟹蟹大佬的打赏，大家一起进步'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.jpg
# 微信二维码图片地址
weixin: /assets/img/wechat.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '你想要的目录~~我还没做呢:)'

# 是否有快速回到顶部的按钮
top: true

#是否开启动画效果
animate: true

# Miscellaneous   
baidu_analytics: '05092b8a7866e4457c613c4a2a294dd0'
google_analytics: 'UA-106082021-1'
favicon: /favicon.png

#你的头像url
avatar: /assets/img/qiaoer.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: tyrantqiao

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  本网站主题yilia设计者的主页: http://litten.me/
#  友情链接2: http://localhost:4000/
#  友情链接3: http://localhost:4000/
#  友情链接4: http://localhost:4000/
#  友情链接5: http://localhost:4000/
#  友情链接6: http://localhost:4000/

aboutme: 练习两年半的程序员，喜欢唱、玩、编程，主要方向是Java，对python、shell、前端都有一定的了解，博客也是尽量将一些个人的笔记，以及觉得有价值的东西进行展示。如果有问题或者想讨论的可以联系tyrantqiao@gmail.com或者tyrantqiao@qq.com
